### ISSUE TITLE
circular dependency scanner has a circular dependency

### ISSUE THREAD

**Issue by m-ghaoui** [emosheeep/fe-tools#2]
```
> ds
info Working directory is 
info Ignored paths: **/node_modules/**
❯ Globbing files with **/*.{js,ts,jsx,tsx,vue,mjs,cjs}
  ⠸ Wait a moment...
◼ Pulling out import specifiers from files...
◼ Analyzing circular dependencies...
ReferenceError: Cannot access '$' before initialization
    at AsyncHook.syncCwd (file:///C:/Users/m.ghaoui/AppData/Roaming/npm/node_modules/circular-dependency-scanner/node_modules/zx/build/core.js:324:5)
    at emitHook (node:internal/async_hooks:235:38)
    at promiseResolveHook (node:internal/async_hooks:364:3)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
❯ Globbing files with **/*.{js,ts,jsx,tsx,vue,mjs,cjs}
  ⠦ Wait a moment...
◼ Pulling out import specifiers from files...
◼ Analyzing circular dependencies...
```

**Comment by emosheeep** [comment]
Could you please give me more informations about your ds version or reproduction？ I can't reproduce it. It seems like an error of 'zx' dependency, maybe you can try to reinstall circular-dependency-scanner(better to use `pnpm i -g`)

**Comment by m-ghaoui** [comment]
Sure! I'm on Windows and I installed it using:

```
npm i -g circular-dependency-scanner
```

The version is:

```
> ds -V
1.1.1
```

As per your suggestion, I installed it using pnpm (instead of npm). I first uninstalled the npm version (donnow if that makes a difference)

```
> npm uninstall -g circular-dependency-scanner

removed 172 packages, and audited 1 package in 773ms

found 0 vulnerabilities
> pnpm i -g circular-dependency-scanner

 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
Downloading registry.npmjs.org/typescript/4.9.4: 11.6 MB/11.6 MB, done
Packages: +176
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\m.ghaoui\AppData\Local\pnpm\store\v3
  Virtual store is at:             .pnpm
Progress: resolved 198, reused 130, downloaded 46, added 176, done

C:\Users\m.ghaoui\AppData\Local\pnpm\global\5:
+ circular-dependency-scanner 1.1.1

The integrity of 2334 files was checked. This might have caused installation to take longer.
Done in 7.2s
> ds
info Working directory is 
info Ignored paths: **/node_modules/**
❯ Globbing files with **/*.{js,ts,jsx,tsx,vue,mjs,cjs}
  ⠸ Wait a moment...
◼ Pulling out import specifiers from files...
◼ Analyzing circular dependencies...
ReferenceError: Cannot access '$' before initialization
    at AsyncHook.syncCwd (file:///C:/Users/m.ghaoui/AppData/Local/pnpm/global/5/.pnpm/zx@7.1.1/node_modules/zx/build/core.js:324:5)
    at emitHook (node:internal/async_hooks:235:38)
    at promiseResolveHook (node:internal/async_hooks:364:3)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
❯ Globbing files with **/*.{js,ts,jsx,tsx,vue,mjs,cjs}
  ✖ Wait a moment...
◼ Pulling out import specifiers from files...
◼ Analyzing circular dependencies...
```

**Comment by m-ghaoui** [comment]
My node version is:

```
> node --version
v16.18.1
```

**Comment by emosheeep** [comment]
Oh~I forgot Windows System, I use MacOS consistantly, maybe there has been some difference, I will make some tests at free time.  Now I have no time because I'm on working.

**Comment by emosheeep** [comment]
I tried to run the command on Windows but everything runs well...I also don't know what happened🤣

![img_v2_5c254bd1-cf38-4573-9461-d413ee9cf85g](https://user-images.githubusercontent.com/31957758/210532305-fcef93b0-66a0-4fba-b2cf-4f0e7a2268ed.gif)

**Comment by m-ghaoui** [comment]
Ok. It must be my machine, then.
